networks:
  food-hub-net:
    driver: bridge

services:

  pgsql:
    build: 
      context: .
      dockerfile: docker/postgresql/Dockerfile
    container_name: "pgsql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pizzaria
    ports:
      - 5432:5432
    networks:
      - food-hub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5      

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: david@live.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 1123:80
    depends_on:
      - pgsql
    links:
      - pgsql
    networks:
      - food-hub-net

  web-api:
    build: 
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: web-api
    ports:
      - 1445:1445
    environment:
      - HOST=localhost
      - PORT=1445
      - POSTGRES_URL=postgresql://postgres:1234@pgsql/pizzaria?schema=public
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - food-hub-net
    links:
      - pgsql    