name: Continuous Integration
on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs: 
    runner-job: 
        runs-on: ubuntu-latest         
        
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4

          - name: Get node.js image
            uses: actions/setup-node@v2
            with: 
              node-version: 20.11.x
          
          - name: Up services with docker compose
            run: docker compose up -d
          
          - name: Build the rest api
            run: |
              npm ci              
              npm run update_prisma
              npm run tsoa:process
              npm run build
          - name: Start the app
            run: |
              npm start
              npm run test
          - run: echo 'Finish pipeline!'


