name: Continuous Integration
on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs: 
    runner-job: 
        runs-on: ubuntu-latest         
        env:
          HOST: localhost
          PORT: 1445
          POSTGRES_URL: postgresql://postgres:1234@pgsql/pizzaria?schema=public

        steps:
          - name: Check out repository code
            uses: actions/checkout@v4         
          
          - name: Up services with docker compose
            run: docker compose up -d
          
          - name: Wait while the system starts
            run: sleep 4

          - name: Run tests
            run: docker exec web-api npm run test
          
          - name: Kill server process
            run: docker compose down
            
          - run: echo 'Finish pipeline!'


